#!/bin/bash

function wake () {
    source wake
    _wake $@
}

function _wake () {
    bname=$(basename $(pwd))
    if [ $bname != "echo-warmer" ]
    then
        echo "wake must be run from the Avenluutn/echo folder"
        return [127]
    fi
    hardhat_abi_path=`pwd`/../hardhat/artifacts/contracts
    abigen_out_path=`pwd`/publisher
    case $1 in
        "abigen")
            echo "running abigen"
            docker run \
                   -u `id -u`:`id -g` \
                   -v $hardhat_abi_path:/sources \
                   -v $abigen_out_path:/out \
                   ethereum/client-go:alltools-latest abigen \
                   --abi /sources/Publisher.sol/Publisher.abi \
                   --out /out/artifact_Publisher_sol.go \
                   --pkg  publisher \
                   --type Publisher \
                   --bin /sources/Publisher.sol/Publisher.bin

            docker run \
                   -u `id -u`:`id -g` \
                   -v $hardhat_abi_path:/sources \
                   -v $abigen_out_path:/out \
                   ethereum/client-go:alltools-latest abigen \
                   --abi /sources/NarratorNFTs.sol/NarratorNFTs.abi \
                   --out /out/artifact_NarratorNFTs_sol.go \
                   --pkg  publisher \
                   --type NarratorNFTs \
                   --bin /sources/NarratorNFTs.sol/NarratorNFTs.bin

            echo "done."
            ;;
        "test")
            go test ./...
            ;;
        "format")
            go fmt
            ;;
        *)
            which wake
            ;;
    esac
}
