import React from 'react'
import { Link } from 'react-router-dom'

export default () => {
  return (
    <>
      <div className="block">
        <div className="block has-text-grey">
          The Grand Adventure is a generative story game that takes place in the {" "}
          <a className="is-underlined has-text-white" href="https://www.lootproject.com/" target="_blank">Lootverse</a>
          . Each season, adventures will seek out quests where they will risk life and limb for glory. 
          Their stories are recorded forever on the pages of their guild logbooks.
        </div>
        <div className="block">
          <h2 className="subtitle is-garamond has-text-white">A Collective Story Generator</h2>
        </div>
        <div className="block has-text-grey">
          The Grand Adventure is a collective story-telling game.
          We plan to increasingly put the direction of The Grand Adventure in the hands of its community. 
          Anyone will be able to participate and shape the future of the stories that are told and the world that emerges.
        </div>
        <div className="block">
          <h2 className="subtitle is-garamond has-text-white">How It Works</h2>
        </div>
        <div className="block has-text-grey">
          Stories are generated by a script using the Ethereum blockchain's blockhashes as pseudorandom seeds. 
          A narrator smart contract schedules these stories to be revealed over time, 
          and a publisher contract auctions them off as NFTs as they are completed. 
          These NFTs record key moments in the stories of the adventurers, but confer no in-game advantage for holders.
          Funds go the Grand Adventure treasury.
        </div>
      </div>
      <Link to="/">
        <div className="is-underlined has-text-white">
          Back
        </div>
      </Link>
    </>
  )
}